services:
  - type: web
    name: eureka-server
    env: docker
    dockerfilePath: ./eureka-server/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  - type: web
    name: gateway-service
    env: docker
    dockerfilePath: ./gateway-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_SERVER_URL
        value: https://eureka-server.onrender.com/eureka
      - key: JWT_SECRET
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: auth-service
    env: docker
    dockerfilePath: ./auth-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_SERVER_URL
        value: https://eureka-server.onrender.com/eureka
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false

  - type: web
    name: profile-content-service
    env: docker
    dockerfilePath: ./profile-content-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_SERVER_URL
        value: https://eureka-server.onrender.com/eureka
      - key: MONGO_URI
        sync: false

  - type: web
    name: media-service
    env: docker
    dockerfilePath: ./media-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_SERVER_URL
        value: https://eureka-server.onrender.com/eureka
      - key: MONGO_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: notification-service
    env: docker
    dockerfilePath: ./notification-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_SERVER_URL
        value: https://eureka-server.onrender.com/eureka
      - key: MONGO_URI
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_TO_EMAIL
        sync: false

  - type: web
    name: analytics-service
    env: docker
    dockerfilePath: ./analytics-service/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_SERVER_URL
        value: https://eureka-server.onrender.com/eureka
      - key: MONGO_URI
        sync: false
