server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      auto-index-creation: true

jwt:
  access-token-expiry-ms: ${JWT_ACCESS_TOKEN_EXPIRY_MS:900000}    # 15 minutes default
  refresh-token-expiry-ms: ${JWT_REFRESH_TOKEN_EXPIRY_MS:604800000} # 7 days default

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
